"""
Postprocessor: safe conditional glued-word repair using wordninja.

PDF files generated by certain broken PDF producers or optical recognition
tools sometimes fail to emit space glyphs between consecutive words, producing
fused strings like "andthemanwenttothestore".

Running wordninja unconditionally across all text can break URLs, email addresses,
code identifiers, domain names, and technical terminology.  TextCleaner applies
strict heuristics to repair ONLY unambiguously fused natural language words.
"""
from __future__ import annotations

import re
import wordninja

from ..models.document_schema import Block, ElementType

# Leading/trailing punctuation to detach before testing token
_PUNCT_STRIP = "\"'`([{<.,;:!?)]}>—–"

# Minimum length of an alphabetic word before considering it glued
_MIN_GLUED_LEN = 18


class TextCleaner:
    @classmethod
    def clean_blocks(cls, blocks: list[Block]) -> list[Block]:
        """
        Scans all text spans in blocks (paragraphs, headings, list items,
        and table cells) and repairs abnormally long fused words.
        Modifies spans in-place and returns the block list.
        """
        for block in blocks:
            # Clean direct spans (paragraphs, headings, list items)
            if block.spans:
                for span in block.spans:
                    if span.text:
                        span.text = cls._repair_text(span.text)

            # Clean table matrix cells
            if block.element_type == ElementType.TABLE and block.table_matrix:
                for row in block.table_matrix:
                    for cell in row:
                        if cell and cell.spans:
                            for span in cell.spans:
                                if span.text:
                                    span.text = cls._repair_text(span.text)

        return blocks

    @classmethod
    def _repair_text(cls, text: str) -> str:
        """Processes whitespace-separated tokens within a string."""
        if not text or len(text) < _MIN_GLUED_LEN:
            return text

        tokens = text.split(" ")
        repaired: list[str] = []

        for token in tokens:
            repaired.append(cls._repair_token(token))

        return " ".join(repaired)

    @classmethod
    def _repair_token(cls, token: str) -> str:
        """Inspects an individual token and splits it if it is a fused word."""
        # Fast exit if token is short
        if len(token) < _MIN_GLUED_LEN:
            return token

        # Skip URLs, email addresses, paths, or code constructs
        if (
            "://" in token
            or "@" in token
            or "/" in token
            or "\\" in token
            or "_" in token
            or "=" in token
            or "#" in token
        ):
            return token

        # Detach leading and trailing punctuation (e.g. "(Gluedwordhere).")
        prefix = ""
        suffix = ""
        core = token

        while core and core[0] in _PUNCT_STRIP:
            prefix += core[0]
            core = core[1:]

        while core and core[-1] in _PUNCT_STRIP:
            suffix = core[-1] + suffix
            core = core[:-1]

        if len(core) < _MIN_GLUED_LEN:
            return token

        # Must be pure alphabetic and not all-uppercase (e.g. acronyms/constants)
        if core.isalpha() and not core.isupper():
            try:
                splits = wordninja.split(core)
                # Only apply if it successfully split into 2 or more words
                if len(splits) > 1:
                    return prefix + " ".join(splits) + suffix
            except Exception:
                pass

        return token
